
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgrpwompxvnuwizzuiyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncnB3b21weHZudXdpenp1aXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjEwNjcsImV4cCI6MjA1OTM5NzA2N30.tEnJRPdQtcWACU_WL__omLkjK6AWI3ILfogExYoHG2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
